paths:
  raw_data: "/path/to/01-raw"
  processed_data: "/path/to/02-processed"
  features: "/path/to/03-features"
  models: "/path/to/04-models"
  exports: "/path/to/05-exports"

project:
  name: fitness-analytics
  timezone: Europe/Bucharest

analysis:
  start_date: 2025-12-07
  end_date: not_set